### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cukal** [GuillaumeSmaha/ansible-role-gluu-setup#4]
Thanks for this excellent role, really a time-saver when deploying Gluu! 
When using Let's Encrypt to generate a key & certs for the HTTP frontend there are 3 files:

```
ca_bundle.crt
certificate.crt
private.key
```

How can these be used in the Ansible setup script to add to the HTTP frontend?

Thanks!
L

**Comment by Yamilquery** [comment]
I would like to know this answer!

**Comment by GuillaumeSmaha** [comment]
If you use a cluster, you can use a nginx frontend to solve it like I am doing here: https://github.com/GuillaumeSmaha/ansible-gluu-playbook/blob/master/cluster-simple/Vagrantfile#L57

Otherwise, you can install the certificate in `/etc/certs` and in the `java key store` (https://gluu.org/docs/gluu-server/2.4.4/admin-guide/certificates/#updating-apache-certificate)
To deploy the http certs with the ansible role, it will need this for each gluu server:
```
gluu_certificates:
    httpd:
      publicKey: "{{ playbook_dir }}/templates/certificates/httpd.crt"
      privateKey: "{{ playbook_dir }}/templates/certificates/httpd.key"
```
Using `certificate.crt` (httpd.crt) and `private.key` (httpd.key) , it seems `ca_bundle.crt` is not necessary for HTTP server
